#!/usr/bin/with-contenv bash


echo "Setting correct permissions"
# permissions
touch /var/log/glusterfs/glusterd.log && \
    chown ${PUID:-911}:${PGID:-911} /var/log/glusterfs/glusterd.log
mkdir /run/gluster/snaps/    
chown -R ${PUID:-911}:${PGID:-911} /run/gluster/snaps

# run initial IP update
#exec \
#	s6-setuidgid abc /app/duck.sh
